
/*******
 MACHINE GENERATED, DO NOT EDIT.
 Generated by gatech.mmpm.tools.IDomainGenerator, written by Marco Antonio Gómez Martín
 *******/
package towers.mmpm;


import gatech.mmpm.sensor.Sensor;


  
/**
 Class for the 'Towers' domain.

 This class is machine-generated. If you have to change anything,
 probably you want to edit the XML file used to create this class.
 @author gatech.mmpm.tools.DomainGenerator, developed by Marco Antonio Gómez Martín
 and David Llanso.
*/
public class TowersDomain implements gatech.mmpm.IDomain {

    public String getName() {
       return getDomainName();
    }

	/* *
	 * Return the world model of the game.
	 * @return World model or null if there is no one.
	 */
/*
    // This was to be a D2 hack. MMPM will not provide that.
    public worldmodel.WorldModel getWorldModel() {
       
       // No specific WorldModel in 'Towers' domain
       // Default used.
       return new worldmodel.WorldModel();
    }
*/

    /**
     * Method that defines all the entities in the domain.
     * @return An array with all the Class'es that implement the
     * D2 entities for the domain.
    */
    public Class<? extends gatech.mmpm.Entity>[] getEntities() {

        Class<? extends gatech.mmpm.Entity> []ret;

        ret = new Class[] {
                    towers.mmpm.entities.TPlayer.class,
                    towers.mmpm.entities.TBase.class,
                    towers.mmpm.entities.TTower.class,
                    towers.mmpm.entities.TUnit.class,
                    towers.mmpm.entities.TUpgradeGold.class,
                    towers.mmpm.entities.TUpgradeUnits.class,
                    towers.mmpm.entities.TWall.class,
                    
              };

        return ret;        
    }

    /**
    * Method that return a new entity generated from its short name class.
    * @return New instance of the specified entity.
    */
    public gatech.mmpm.Entity getEntityByShortName(char shortName, String entityId, String owner) {

        gatech.mmpm.Entity ret;

        switch (shortName) {
        
            case 'w':
                ret = new towers.mmpm.entities.TWall(entityId,owner);
            break;
          
      default: ret = null;
      };

      return ret;
      }

      /**
      * Method that return a new entity generated from its name class.
      * @return New instance of the specified entity.
      */
      public gatech.mmpm.Entity getEntityByName(String name, String entityId, String owner) {
      
        if( name.equals("TPlayer") )
        return new towers.mmpm.entities.TPlayer(entityId,owner);
      
        if( name.equals("TBase") )
        return new towers.mmpm.entities.TBase(entityId,owner);
      
        if( name.equals("TTower") )
        return new towers.mmpm.entities.TTower(entityId,owner);
      
        if( name.equals("TUnit") )
        return new towers.mmpm.entities.TUnit(entityId,owner);
      
        if( name.equals("TUpgradeGold") )
        return new towers.mmpm.entities.TUpgradeGold(entityId,owner);
      
        if( name.equals("TUpgradeUnits") )
        return new towers.mmpm.entities.TUpgradeUnits(entityId,owner);
      
        if( name.equals("TWall") )
        return new towers.mmpm.entities.TWall(entityId,owner);
      
        return null;
    }

    /**
     Method that defines all the actions in the domain.
     @return An array with all the Class'es that implement the
     D2 actions for the domain.
    */
    public Class[] getActions() {
        Class []ret;

        ret = new Class[] {
                    towers.mmpm.actions.Accept.class,
                    towers.mmpm.actions.Build.class,
                    
              };

        return ret;        
    }

    /**
     Method that defines all the sensors in the domain.
     @return An array with all sensors.
    */
    public Sensor[] getSensors() {
        Sensor []ret;

        ret = new Sensor[] {
                     
                        new towers.mmpm.sensors.BuildableCoordinates(),
                     
                        new towers.mmpm.sensors.NonBlockingPath(),
                     
                        new towers.mmpm.sensors.Gold(),
                     
                        new towers.mmpm.sensors.BuildingCost(),
                     
              };

        return ret;        
    }

    /**
     Method that defines all the goals in the domain.
     @return An array with all goals.
    */
    public Sensor[] getGoals() {
        Sensor []ret;

        ret = new Sensor[] {
           
                        new towers.mmpm.goals.WinGoal()
             
              };

        return ret;        
    }

    /**
     Method that return the win goal condition.

     @return An object (Sensor) that represent the win goal.
    */
    public Sensor getWinGoal() {
       
       return new towers.mmpm.goals.WinGoal();
    }

    // This static method could be used in the game
    // itself; it is not forced by the gatech.mmpm.IDomain interface
    public static String getDomainName() {
        return "Towers";
    }

	// Someone included this method in gatech.mmpm.domain
	// and did not
	// update the domain generation tool.
	// A hack has been done: the generation tool
	// implements this method returning always null.
	// If this is important, then the XML with the
	// game domain should include the value to be
	// returned here, and the tool should be updated.
	public String getRulesFile() {
		return null;
	}
}
